# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_btn = QtWidgets.QPushButton(self.centralwidget)
        self.map_btn.setEnabled(True)
        self.map_btn.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.map_btn.setMouseTracking(False)
        self.map_btn.setTabletTracking(False)
        self.map_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.map_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.map_btn.setAutoDefault(False)
        self.map_btn.setObjectName("map_btn")
        self.sput_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sput_btn.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.sput_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sput_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.sput_btn.setObjectName("sput_btn")
        self.gibr_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gibr_btn.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.gibr_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gibr_btn.setObjectName("gibr_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 100, 661, 461))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 60, 351, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 60, 111, 21))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(100, 50, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(100, 30, 171, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 171, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 30, 471, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.map_btn.setText(_translate("mainWindow", "cхема"))
        self.sput_btn.setText(_translate("mainWindow", "спутник"))
        self.gibr_btn.setText(_translate("mainWindow", "гибрид"))
        self.lineEdit.setText(_translate("mainWindow", "Поиск объекта"))
        self.pushButton.setText(_translate("mainWindow", "сброс результата"))
        self.radioButton.setText(_translate("mainWindow", "нет"))
        self.radioButton_2.setText(_translate("mainWindow", "да"))
        self.label_2.setText(_translate("mainWindow", "  показывать почтовый индекс"))
        self.label_3.setText(_translate("mainWindow", "Адрес"))
